  
name: Build and Push

on:
  push:
    branches: master

env:
  WAYPOINT_SERVER_TOKEN: bM152PWkXxfoy4vA51JFhR7LoCDtMFhBgvRewMJ4sZvbft1KE7mEoZBRQqYvRC9RZCnmBsmGk2MopuNoEs179VLKcSNiGWvRvDN6k
  WAYPOINT_SERVER_ADDR: 192.168.199.130:26818
  WAYPOINT_SERVER_TLS: 1
  WAYPOINT_SERVER_TLS_SKIP_VERIFY: 1

jobs:
  bp:
    name: Build and push
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: setup waypoint
        uses: hashicorp/action-setup-waypoint
        with:
            version: '0.1.0'
     
     - name: Waypoint init
       run : waypoint init

     - name: Waypoint build
       run : waypoint build
                       
            
